### ISSUE TITLE
Sometimes *OPC? times out on a slow system with VNA Simulator

### ISSUE THREAD

**Issue by alan-copeland-keysight** [opentap/Network-Analyzer#161]
Changing the Default timeout to 5 seconds seems to fix this issue. 5 seconds seems reasonable. What do you think @c-montes ?

**Comment by c-montes** [comment]
Sounds good, I have seen that also when remote connecting to real instruments located in a different site. Even 10 seconds should be better.

There is an issue which I have not completed from a while ago #34, The idea is to present a WPF dialog box that shows a spinner and a message indicating we are waiting on the instrument, this also takes care of the slow systems. I may need to complete this soon. But for now increase the default to 5 seconds seems good to me.
